version: '3'

services:
  bunapp-api-db:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5439:5439'
    volumes:
      - 'pgdata:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=root'
      - 'POSTGRESQL_PASSWORD=root'
      - 'POSTGRESQL_DATABASE=bunapp'

volumes:
  pgdata:
    driver: local
