version: '2'

services:
  chad-integration-db:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=root'
      - 'POSTGRESQL_PASSWORD=root'
      - 'POSTGRESQL_DATABASE=chad_integration'

volumes:
  pgdata:
    driver: local
